#!/bin/bash
# Argument parsing
ssh_base_command="ssh"
while [[ $# -gt 0 ]]; do
    case $1 in
        -p) ssh_base_command+=" -p $2"; shift ;;
        -l) ssh_base_command+=" -l $2"; shift ;;
        -i) ssh_base_command+=" -i $2"; shift ;;
        -X) ssh_base_command+=" -X" ;;
        -L) ssh_base_command+=" -L $2:localhost:$2"; shift;;
        -C) ssh_base_command+=" -C" ;;
        -D) ssh_base_command+=" -D $2"; shift;;
        *) break ;;
    esac
    shift
done

# Main script starts here
initial_host=$1
# Functions
get_ssh_config_block() {
    local initial_host="$1"
    local config=$(awk -v host="$initial_host" '
        BEGIN { found = 0; print_block = 0; }
        /^Host / {  # This regex matches lines that exactly start with "Host " followed by a space
            if ($2 == host) {
                found = 1;  # Start of the desired host block
                print_block = 1;  # Enable printing
            } else if (found) {
                print_block = 0;  # If another host block starts and weve already found our block, stop printing
                exit;  # Exit the program as were done printing the desired block
            }
        }
        print_block { print; }  # Print lines of the current block
        ' ~/.ssh/config)
    
    if [ -n "$config" ]; then
        echo "$config"
    else
        echo "No configuration found for host: $initial_host"
    fi
}
determine_sshpass_prompt_pw() {
  local host="$1"
  opt_pw=$(security find-generic-password -s "$host" -w)
  if [ -n "$opt_pw" ]; then
    # echo "pw not "
    echo "sshpass -p $opt_pw"
  else
    echo ""
    # echo "pw found"
  fi
}

# Logic
config=$(get_ssh_config_block "$initial_host")
user=$(echo "$config" | grep -o "User [^ ]*" | awk '{print $2}')
jump_needed=$(echo "$config" | grep -o "ProxyJump [^ ]*" | awk '{print $2}')
hostname_var=$(echo "$config" | grep -o "HostName [^ ]*" | awk '{print $2}')
echo "Connecting to $initial_host with $hostname_var"


lab_list=("smart" "netserv1")
ikr_cent_list=("cnode01" "ingress" "cnode09")

# Get password from secure storage on macOS
if [[ " ${lab_list[@]} " =~ " $initial_host " ]]; then
  echo "host on lab list"
  if [ $(uname) == "Darwin" ]; then
    echo "On mac so using docker to execute knock"
    ~/nbin/libscripts/docker_knock_lab
  else 
    ~/nbin/libscripts/knock_lab --target "$hostname_var"
  fi
fi

if [[ " ${ikr_cent_list[@]} " =~ " $initial_host " ]]; then
  echo "host on ikr"
  if [ $(uname) == "Darwin" ]; then
    # echo "On mac so using docker to execute knock"
    ~/nbin/knock_ikr_mac
  else 
    ~/nbin/libscripts/knock_ikr_linux
  fi
fi

# Determine the full SSH command
sshcommand="$ssh_base_command $initial_host"
sshpass_command=$(determine_sshpass_prompt_pw "$initial_host")
# echo "Debug sshpass: $sshpass_command"
echo "SSH-Command: $sshcommand"
if [ -n "$jump_needed" ]; then
  echo "Jump needed statement "
  jump_pw=$(security find-generic-password -s "$jump_needed" -w)
  pw=$(security find-generic-password -s "$initial_host" -w)
  # echo "sshpass -d 123 $ssh_base_command -o ProxyCommand=\"sshpass -p $jump_pw ssh -W %h:%p $jump_needed\"  $user@$hostname_var 123<<<$pw"

  sshpass -d 123 $ssh_base_command -o ProxyCommand="sshpass -p $jump_pw ssh -W %h:%p $jump_needed"  "$user@$hostname_var" 123<<<"$pw"
else
  $sshpass_command $sshcommand
fi
