display_full_path = false
search_submodules = true
session_sort_order ="LastAttached"

[[search_dirs]]
path = "~/source"
depth = 10

[[search_dirs]]
path = "~/dotfiles_ikr/"
depth = 1

[[search_dirs]]
path = "~/source/mdppaper/"
depth = 10

[[search_dirs]]
path = "~/secondBrain"
depth = 10

[shortcuts]
"ctrl-k" = "move_up"
"ctrl-j" = "move_down"
"ctrl-h" = "cursor_left"
"ctrl-l" = "cursor_right"
