general.live_config_reload = true
# theme = "Catppuccin"
general.import =[
"~/.config/alacritty/catppuccin-macchiato.toml"
] 
[bell]
animation = "EaseOutExpo"
duration = 0
[cursor]
style = "Beam"
# blinking="on"
[colors]
draw_bold_text_with_bright_colors = true

# [[colors.indexed_colors]]
# color = "0xF8BD96"
# index = 16
#
# [[colors.indexed_colors]]
# color = "0xF5E0DC"
# index = 17
#
# [colors.bright]
# black = "0x988BA2"
# blue = "0x96CDFB"
# cyan = "0x89DCEB"
# green = "0xABE9B3"
# magenta = "0xF5C2E7"
# red = "0xF28FAD"
# white = "0xD9E0EE"
# yellow = "0xFAE3B0"
#
# [colors.cursor]
# cursor = "0xF5E0DC"
# text = "0x1E1D2F"
#
# [colors.normal]
# black = "0x6E6C7E"
# blue = "0x96CDFB"
# cyan = "0x89DCEB"
# green = "0xABE9B3"
# magenta = "0xF5C2E7"
# red = "0xF28FAD"
# white = "0xD9E0EE"
# yellow = "0xFAE3B0"
#
# [colors.primary]
# background = "0x1E1D2F"
# foreground = "0xD9E0EE"
#
[env]
TERM = "xterm-256color"

[font]
size = 12
# builtin_box_drawing = false

[font.bold]
family = "MonoLisa nh"
style = "Bold"

# [font.underline]
# family = "MonoLisa script"
# style = "underline"
# [font.glyph_offset]
# x = 0
# y = 0

[font.italic]
family = "MonoLisa nh"

[font.normal]
# family = "Jetbrains Mono NF"
# family = 'MesloLGS Nerd Font Mono'
family= "MonoLisa nh"
style = "Regular"

# [font.offset]
# x = 0
# y = 0

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# [mouse.double_click]
# threshold = 300

# [mouse.triple_click]
# threshold = 300

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "Buttonless"
dynamic_title = true
# option_as_alt = "Both"
startup_mode = "Maximized"

opacity = 0.95

[window.dimensions]
columns = 160
lines = 80

[window.padding]
x = 4
y = 4
